Added chart displaying historical data for selected smartbin
Joppevalck/II1302-projekt pull request #33
Opened 2021-05-17 15:48 UTC by willeasp

- clicking on a smartbin card runs the initBigChart function from the specified deviceId
- initBigChart calls api to get data about specific device
- getChartAxes fits the data on a linear "timeline" having the data displayed correctly relative to each other
- clicking on an already selected card removes the chart

2021-05-17 18:25 UTC, joakgus reviewed
Jag vill diskutera minna kommentarer innan jag säger ok.

2021-05-17 20:13 UTC, willeasp commented on webapp/src/views/Dashboard.vue
> +        if (this.selectedDevice == deviceId)
Jag satte == medvetet, för att dataobjekten använder strängar men man ska kunna skicka in siffror till funktionen och det fortfarande ska fungera!

2021-05-17 20:14 UTC, willeasp commented on webapp/src/views/Dashboard.vue
> +        return result;
Ja det håller jag med om, hade kvar det från koden jag testade med.

2021-05-17 20:14 UTC, willeasp commented on webapp/src/views/Dashboard.vue
> +                label: 'Performance',
Absolut, glömde ändra det

2021-05-18 14:05 UTC, joakgus submitted a review, later dismissed
Looks good!

2021-05-18 14:49 UTC, Joppevalck requested changes

2021-05-18 14:49 UTC, Joppevalck commented on webapp/src/cosmos/cosmos.js
> +    // async getDevice(deviceId){
Remove get device and get all data

2021-05-18 14:50 UTC, Joppevalck approved these changes

2021-05-18 14:51 UTC, merged